export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as AllCampuses} from './AllCampuses'
export {default as SingleCampus} from './SingleCampus'
export {default as AddCampus} from './AddCampus'
export {default as AllStudents} from './AllStudents'
export {default as SingleStudent} from './SingleStudent'
export {default as AddStudent} from './AddStudent'
